version: '3.8'
services:
    jpf:
        build:
            context: .
            dockerfile: DockerFile
        image: jpf-dockerized

        stdin_open: true
        tty: true
        volumes:
            - ./example-code:/code
